package com.taotao.mapper;

import com.taotao.pojo.Test;
import com.taotao.pojo.TestExample;
import java.util.List;
//import org.apache.ibatis.annotations.Param;

public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    long countByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    int deleteByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    int insert(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    int insertSelective(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    List<Test> selectByExample(TestExample example);

//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table test
//     *
//     * @mbg.generated
//     */
//    int updateByExampleSelective(@Param("record") Test record, @Param("example") TestExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table test
//     *
//     * @mbg.generated
//     */
//    int updateByExample(@Param("record") Test record, @Param("example") TestExample example);
}