spring:
  # DB
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taotao?characterEncoding=utf-8
    username: root
    password: 123456

mybatis:
  # mybatis 逆向工程
  generator:
    targetPackage:
      dao: com.taotao.dao
      mapper: com.taotao.mapper
      pojo: com.taotao.pojo